# Generated by Django 6.0.5 on 2026-05-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dizlikes',
            field=models.IntegerField(default=0),
        ),
    ]
