# Generated by Django 6.0.5 on 2026-06-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_direct'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_delete',
            field=models.SlugField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
