# Generated by Django 6.0.5 on 2026-06-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_is_delete_message_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
