# Generated by Django 6.0.5 on 2026-06-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='direct/'),
        ),
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mesage/'),
        ),
    ]
