# Generated by Django 6.0.5 on 2026-06-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_direct_photo_message_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='voice/'),
        ),
    ]
