# Generated by Django 6.0.5 on 2026-06-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_voice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='voice',
        ),
        migrations.AddField(
            model_name='direct',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='voice/'),
        ),
    ]
