# Generated by Django 6.0.5 on 2026-06-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_message_voice_direct_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direct',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
