# Generated by Django 6.0.5 on 2026-06-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('voice', 'Voice'), ('missed_call', 'Missed Call')], default='text', max_length=20),
        ),
    ]
