# Generated by Django 6.0.5 on 2026-05-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='celery_task_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
