# Generated by Django 6.0.5 on 2026-06-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_scores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scores',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
