# Generated by Django 6.0.5 on 2026-06-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_delete_scores_appointment_is_delete_appointment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
