# Generated by Django 6.0.5 on 2026-06-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_remove_appointment_is_delete_appointment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sms_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
